BORROW_YAW_MAX_DIST_M: 3.898110642470292
BOTTOM_STRIP_FRAC: 0.4
CLUSTER_EPS_M: 0.6
CLUSTER_MIN_PTS: 8
DET_CONF: 0.46923415306724614
DET_IOU: 0.7177978419074074
FUSE_POST_SUPPRESS: false
FUSE_SUPPRESS_DIST_M: 1.2
FUSE_SUPPRESS_KEEP_BY: score
FUSE_WEIGHT_BY_SUPPORT: true
GROUND_Z_MARGIN: 0.30774109475211825
GROUND_Z_PERCENTILE: 29
GT_CLUSTER_THR_M: 1.0
MAX_RANGE_KEEP: 127.96787323066997
MERGE_OVERLAP_MIN: 0.06373090823626923
MIN_LIDAR_PTS_IN_BOX: 9
MIN_RANGE_KEEP: 4.0990329001710055
MIN_YAW_PTS: 31
MIN_Z_CAM_VIS: 0.2
MODEL_YOLO: yolov8x.pt
NMS_IOU_AGNOSTIC: 0.7
PAIR_GATE_M: 2.1473339376146363
REMOVE_SELF_FROM_YOLO: true
SELF_MASK_AGENTS:
- '0'
- '1'
SELF_MASK_IOU_THR: 0.3454907346635775
SHAPE_EIG_RATIO_MIN: 2.3422092358542175
SWAP_XY_OCC: false
TRIM_YAW_KEEP_SCALE: 0.8850375645944218
TRIM_YAW_MIN_KEEP: 8
TRIM_YAW_SLACK_M: 0.47304080339648125
TRIM_YAW_XY: true
USE_BOTTOM_STRIP: false
USE_CLASS_AGNOSTIC_NMS: false
USE_CLASS_PRIOR_90_DISAMBIG: false
USE_CLUSTER_FOR_CENTER: false
USE_MINAREARECT_YAW: false
USE_PCA_FALLBACK_YAW: true
VALID_GT_CLASSES:
- car
- van
- truck
- bus
- concretetruck
YAW_OFFSET_DEG: 0.0
YAW_USE_FULL_BOX: true
YOLO_VEHICLE_CLASSES:
- car
- van
- truck
- bus
